---
## YAML based inventory, see:
## https://docs.ansible.com/ansible/latest/plugins/inventory/yaml.html
#
kvmhost:
  hosts:
    ## Put your KVM host connection and settings here
    ognongle.home.arpa:
      ansible_host: ognongle.home.arpa
    ## We are emulating multiple KVM hosts here, defaults to localhost
    ## Update them to use real hostnames, or
    ## change ansible_connection to ansible_host with an IP
    nuc10i7fnh.home.arpa:
      ansible_host: nuc10i7fnh.home.arpa
  vars:
    ansible_python_interpreter: /usr/bin/python3
    # Networks are a list, you can add more than one
    # You can create and remove NAT networks on kvmhost (creating bridges not supported)
    # The 'default' network is the standard one shipped with libvirt
    # By default we don't remove any networks (empty absent list)
    virt_infra_host_networks:
      absent:
        - name: default
      present:

puppetserver:
  hosts:
    ## Put your KVM host connection and settings here
    vault.home.arpa:
      ansible_host: vault.home.arpa
  vars:
    ansible_python_interpreter: /usr/bin/python3

vm:
  vars:
    virt_infra_distro: debian
    virt_infra_distro_release: 12
    virt_infra_distro_image: debian-12-genericcloud-amd64.qcow2
    # Run virt-customize with the following arguments
    virt_infra_virt_customize_flags:
      - flag: "install"
        args: "cloud-init"
      - flag: "install"
        args: "qemu-guest-agent"
      - flag: "write"
        args: "/etc/hostname:{{ inventory_hostname }}"
      - flag: "copy-in"
        args: "/home/user/src/puppet-control-repo/provisioning/templates/sources.list:/etc/apt"
        # Fix non-free split warning More information about this can be found online in the Release notes at:
        # https://www.debian.org/releases/bookworm/amd64/release-notes/ch-information.html#non-free-split
      - flag: "copy-in"
        args: "/home/user/src/puppet-control-repo/provisioning/templates/no-bookworm-firmware.conf:/etc/apt/apt.conf.d"
      - flag: "mkdir"
        args: "/opt/ansible_data"
      - flag: "copy-in"
        args: "{{ virt_infra_host_puppet_path }}/{{ virt_infra_puppet_package }}:/opt/ansible_data"
      - flag: "copy-in"
        args: "{{ csr_attributes_file }}:/opt/ansible_data"
    virt_infra_disk_size: 5
    virt_infra_distro_image_url: https://cloud.debian.org/images/cloud/bookworm/latest/debian-12-genericcloud-amd64.qcow2
    virt_infra_security_driver: apparmor
    virt_infra_network_config: true
    virt_infra_user: user
    virt_infra_ssh_pwauth: false
    virt_infra_add_ssh_config: false
    virt_infra_add_etc_hosts: false
    virt_infra_host_puppet_path: "/home/user/Downloads"
    virt_infra_puppet_repository: http://apt.puppet.com
    virt_infra_puppet_package: puppet8-release-bullseye.deb
    # install puppet and fix the hostname in the image
    virt_infra_cloud_init_runcmd:
      - "chown root:root /etc/apt/sources.list /etc/apt/apt.conf.d/no-bookworm-firmware.conf"
      - "chmod 644 /etc/apt/sources.list /etc/apt/apt.conf.d/no-bookworm-firmware.conf"
      - "dpkg -i /opt/ansible_data/{{ virt_infra_puppet_package }} && apt update && apt install -y puppet-agent"
      - "echo {{ inventory_hostname }} > /etc/hostname"
      - "echo 127.0.1.1 {{ inventory_hostname }} {{ inventory_hostname_short }} >> /etc/hosts"
      - "hostname -F /etc/hostname"
      - "mv /opt/ansible_data/csr_attributes.yaml /etc/puppetlabs/puppet"
      - "chown root:root /etc/puppetlabs/puppet/csr_attributes.yaml"
      - "chmod 600 /etc/puppetlabs/puppet/csr_attributes.yaml"
      - "/opt/puppetlabs/bin/puppet config set server vault.home.arpa --section main"
      - "/opt/puppetlabs/bin/puppet resource service puppet ensure=running enable=true"
      - "/opt/puppetlabs/bin/puppet ssl bootstrap --waitforlock 30s"
      - "/opt/puppetlabs/bin/puppet agent --test --waitforlock 30s"
  children:
    deactivated:
      hosts:
        test-debian12-1.home.arpa:
        test-debian12-2.home.arpa:
        test-debian12-3.home.arpa:
        test-debian12-4.home.arpa:
        test-debian12-5.home.arpa:
      vars:
        kvmhost: ognongle.home.arpa
        puppetserver: vault.home.arpa
        virt_infra_state: undefined
    ognongle:
      hosts:
        test-debian12-6.home.arpa:
        test-debian12-7.home.arpa:
      vars:
        kvmhost: ognongle.home.arpa
        puppetserver: vault.home.arpa
        virt_infra_networks:
          - name: br0
            type: bridge
            model: virtio
    # nuc10i7fnh:
    #   hosts:
    #     test-debian12-2:
    #   vars:
    #     kvmhost: nuc10i7fnh.home.arpa
