#!/bin/bash

set -x

R10K=/opt/puppetlabs/server/data/puppetserver/jruby-gems/bin/r10k
PUPPET=/opt/puppetlabs/puppet/bin/puppet
CONFDIR=/etc/puppetlabs/puppet
CODEDIR=/etc/puppetlabs/code
VARDIR=/opt/puppetlabs/puppet/cache

BRANCH=production

while read oldrev newrev ref
do
    # only checking out the master
    if [[ $ref = refs/heads/$BRANCH ]];
    then
        echo "Ref $ref received. Deploying ${BRANCH} branch..."
        sudo -u puppet $R10K deploy environment --modules -v info
        sudo -u puppet $PUPPET generate types \
            --environment $BRANCH \
            --confdir $CONFDIR \
            --codedir $CODEDIR \
            --vardir $VARDIR
    else
        echo "Ref $ref received. Doing nothing: only the ${BRANCH} branch may be deployed on this server."
    fi
done
